project:
  type: website
  output-dir: docs


website:
  title: "BioMolicWeb"
  description: "I am a scientist"
  site-url: https://github.com/mgomezv26
  repo-url: https://github.com/mgomezv26/BioMolicWeb
  # favicon: logo.png
  twitter-card: true
  #   creator: "@handle"
  #   site: "@handle"
  open-graph: true
  # google-analytics:
  #   tracking-id: "UA-XXXXXXXX"
  #   anonymize-ip: true
  # cookie-consent: true


  navbar:
    right:
      - href: index.qmd
        text: Home
      - Projects.qmd
      - Publications.qmd
      - about.qmd

      - icon: rss
        href: index.xml
      - icon: twitter
        href: https://twitter.com

  page-footer:
    background: light
    right: "Made with Quarto"
  # back-to-top-navigation: true


format:
  html:
    theme: quartz
    css: styles.css
    toc: false

execute:
  freeze: auto  # re-render only when source changes



